name: flutter_auth_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  # retrofit: ^2.0.0
  json_annotation: ^4.0.0
  # equatable: ^3.2.6
  # bloc: ^7.3.0
  # flutter_bloc: ^7.3.0
  # dio: ^4.0.0
  retrofit: ^4.1.0
  dio: ^5.4.0
  logger: ^2.3.0
  equatable: ^2.0.5
  shared_preferences: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  retrofit_generator: ^8.1.2
  build_runner: ^2.4.7

flutter:
  uses-material-design: true